export const INDEXLIST = 'INDEXLIST'
export const NORMALIZE_FIXEDTASKDATA = 'NORMALIZE_FIXEDTASKDATA'
export const FIXEDTASKTEMPDATA = 'FIXEDTASKTEMPDATA'
export const TASKITEMSDATA = "TASKITEMSDATA"
// export const  INDEXLIST = 'INDEXLIST'